import { Container } from '@/components/ui/Container';
import { publicPageMetadata } from '@/lib/site';

export const metadata = publicPageMetadata('Privacidade', 'Como a Damazio Atelier trata dados em solicitações de peças sob encomenda.', '/privacidade');

export default function PrivacidadePage() {
  return <main id="conteudo" tabIndex={-1}><section className="institutional-hero legal-page"><Container><p className="eyebrow">Privacidade</p><h1>Como cuidamos das suas informações</h1><p>Quando você envia uma solicitação, usamos os dados informados para entender a peça desejada, responder ao pedido, organizar o atendimento e manter o registro necessário da conversa.</p><h2>Dados e referências enviados</h2><p>Nome, contato, cidade, estado, detalhes da criação e imagens de referência são tratados somente para o atendimento da solicitação. As imagens ficam em armazenamento privado e não são publicadas no catálogo.</p><h2>Notificação por e-mail</h2><p>Os dados da solicitação ficam armazenados no Supabase e podem ser transmitidos ao Gmail somente para notificar a Damazio Atelier e responder ao pedido, pelo endereço damazioatelier@gmail.com. Referências visuais permanecem no armazenamento privado e não são anexadas ao e-mail.</p><h2>Conversa pelo Instagram</h2><p>Depois do envio, o atendimento pode continuar no Instagram Direct. Essa conversa também segue as regras de privacidade da plataforma Instagram; recomendamos que você consulte a política da plataforma antes de compartilhar novos dados por lá.</p><h2>Retenção e seus direitos</h2><p>Guardamos os dados pelo tempo necessário para responder, acompanhar e registrar a solicitação, respeitando obrigações aplicáveis. Para pedir acesso, correção, eliminação ou esclarecimentos sobre seus dados, use o canal de contato que será informado pela Damazio Atelier antes do lançamento.</p><h2>Consentimento e pré-requisito de lançamento</h2><p>O envio da solicitação exige seu consentimento para este tratamento. Antes da publicação do site, a Damazio Atelier deve informar o responsável pelo tratamento, CNPJ, endereço e canal de contato para titulares, além de submeter esta política à revisão jurídica adequada.</p></Container></section></main>;
}

